import type { Metadata } from "next";
import { Footer, Header, Sidenav } from "@/components";
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-col h-screen bg-white text-black">

      {/* Mostrar solo si el usuario está autenticado */}
      <SignedIn >
      
      {/* Redirigir al inicio de sesión si el usuario no está autenticado */}

      <Header />
      <div className="flex-1 flex overflow-hidden">
      <Sidenav/>
        {children}
      </div>
      <Footer />
      </SignedIn>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
    </main>
  );
}
